<?xml version="1.0"?>

<valgrindoutput>

<protocolversion>4</protocolversion>
<protocoltool>memcheck</protocoltool>

<preamble>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
</preamble>

<pid>...</pid>
<ppid>...</ppid>
<tool>memcheck</tool>

<args>
  <vargv>...</vargv>
  <argv>
    <exe>./client-msg</exe>
  </argv>
</args>

<status>
  <state>RUNNING</state>
  <time>...</time>
</status>

<clientmsg>
  <tid>...</tid>
  <text>hello &lt;&gt; &lt;&amp;&gt;%s world
  </text>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>VALGRIND_PRINTF_BACKTRACE</fn>
      <dir>...</dir>
      <file>valgrind.h</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>baz</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>bar</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>foo</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>main</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
  </stack>
</clientmsg>

<status>
  <state>FINISHED</state>
  <time>...</time>
</status>

<heap_summary>
  <memory_in_use_at_exit>
    <bytes>0</bytes>
    <in_blocks>0</in_blocks>
  </memory_in_use_at_exit>
  <total_heap_usage>
    <allocs>0</allocs>
    <frees>0</frees>
    <bytes_allocated>0</bytes_allocated>
  </total_heap_usage>
</heap_summary>

<all_heap_blocks_freed>true</all_heap_blocks_freed>

<errorcounts>
</errorcounts>

<suppcounts>...</suppcounts>

<error_summary>
  <errors>0</errors>
  <from>0</from>
  <suppressed>0</suppressed>
  <suppressed_from>0</suppressed_from>
</error_summary>

</valgrindoutput>
