File descriptor 1020 was closed already
   at 0x........: write (in /...libc...)
   by 0x........: __printf_buffer_flush_dprintf (in /...libc...)
   by 0x........: __vdprintf_internal (in /...libc...)
   by 0x........: dprintf (in /...libc...)
   by 0x........: main (track_new.c:15)
 Previously closed
   at 0x........: close (in /...libc...)
   by 0x........: main (track_new.c:10)
 Originally opened
   at 0x........: open (in /...libc...)
   by 0x........: main (track_new.c:8)
