force page-in by printing this: 0
page 0x..., is guardpage: 0, present: 1
accessing address 0x... passed
Installing guard page, addr=0x...
page 0x..., is guardpage: 1, present: 0
accessing address 0x... failed
Removing guard page, addr=0x...
force page-in by printing this: 0
page 0x..., is guardpage: 0, present: 1
accessing address 0x... passed
Installing guard page, addr=0x...
page 0x..., is guardpage: 1, present: 0
accessing address 0x... failed
page 0x..., is guardpage: 0, present: 0
accessing address 0x... failed
