#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                |

# Remove "Cachegrind, ..." line and the following copyright line.
sed "/^Cachegrind, a cache and branch-prediction profiler/ , /./ d"
